services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: pkuo
      MYSQL_PASSWORD: 123456
      max_allowed_packet: 16777216
      MYSQL_DATABASE: hackathon # 添加默认数据库
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - shared_network

volumes:
  mariadb_data:
    driver: local

networks:
  shared_network:
    external: true
